coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 0%
    patch:
      default:
        target: 100%
        threshold: 0%

ignore:
  - "**/*.g.dart"

codecov:
  require_ci_to_pass: false
  require_changes: no
  token: f0060104-72a0-435f-af1e-9d504a1db9ac
