name: {{name_plural.snakeCase()}}_repository
description: A repository managing the {{name_plural.titleCase()}} domain.
version: 0.0.1

environment:
  sdk: ^3.5.0

dependencies:
  equatable: ^2.0.7
  standard_repositories: ^0.0.1-dev.2

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
