name: Standard Repositories Bloc

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/standard_repositories_bloc_verify_and_test.yaml"
      - "packages/standard_repositories_bloc/**"

  push:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/**"
      - "packages/standard_repositories_bloc/**"


jobs:
  verify_and_test:
    name: Verify and Test
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@main
    with:
      working_directory: packages/standard_repositories_bloc
      dart_sdk: stable
      min_coverage: 0
